---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/runtime-image: "true"
  annotations:
    opendatahub.io/runtime-image-url: "https://github.com//opendatahub-io/notebooks/tree/main/runtimes"
    opendatahub.io/runtime-image-name: "Datascience with Python 3.11 (UBI9)"
    opendatahub.io/runtime-image-desc: "Datascience runtime image for Elyra, enabling pipeline execution from Workbenches with a set of advanced AI/ML data science libraries, supporting different runtimes for various pipeline nodes."
  name: runtime-datascience
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations:
        # language=json
        opendatahub.io/runtime-image-metadata: |
          [
            {
              "display_name": "Datascience with Python 3.11 (UBI9)",
              "metadata": {
                "tags": [
                  "datascience"
                ],
                "display_name": "Datascience with Python 3.11 (UBI9)",
                "image_name": "quay.io/opendatahub/workbench-images@sha256:303afa65c2e61a9a841e6d58dc1d317121c868d342850d789135307301df16c2",
                "pull_policy": "IfNotPresent"
              },
              "schema_name": "runtime-image"
            }
          ]
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
      from:
        kind: DockerImage
        name: quay.io/opendatahub/workbench-images@sha256:303afa65c2e61a9a841e6d58dc1d317121c868d342850d789135307301df16c2
      name: "datascience"
      referencePolicy:
        type: Source
