---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/runtime-image: "true"
  annotations:
    opendatahub.io/runtime-image-url: "https://github.com//opendatahub-io/notebooks/tree/main/runtimes"
    opendatahub.io/runtime-image-name: "Pytorch with CUDA and Python 3.11 (UBI9)"
    opendatahub.io/runtime-image-desc: "PyTorch runtime image for Elyra, enabling pipeline execution from Workbenches with PyTorch libraries and dependencies, supporting different runtimes for various pipeline nodes."
  name: runtime-pytorch
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations:
        # language=json
        opendatahub.io/runtime-image-metadata: |
          [
            {
              "display_name": "Pytorch with CUDA and Python 3.11 (UBI9)",
              "metadata": {
                "tags": [
                  "pytorch"
                ],
                "display_name": "Pytorch with CUDA and Python 3.11 (UBI9)",
                "image_name": "quay.io/opendatahub/workbench-images@sha256:c543a09ef18f86eaa01f1ee1165271ec65dbac969341e5e6c03865f33e1314eb",
                "pull_policy": "IfNotPresent"
              },
              "schema_name": "runtime-image"
            }
          ]
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
      from:
        kind: DockerImage
        name: quay.io/opendatahub/workbench-images@sha256:c543a09ef18f86eaa01f1ee1165271ec65dbac969341e5e6c03865f33e1314eb
      name: "pytorch"
      referencePolicy:
        type: Source
