---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/runtime-image: "true"
  annotations:
    opendatahub.io/runtime-image-url: "https://github.com//opendatahub-io/notebooks/tree/main/runtimes"
    opendatahub.io/runtime-image-name: "Python 3.11 (UBI9)"
    opendatahub.io/runtime-image-desc: "Minimal runtime image for Elyra, enabling pipeline execution from Workbenches with minimal dependency set to start experimenting with, for various pipeline nodes."
  name: runtime-minimal
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations:
        # language=json
        opendatahub.io/runtime-image-metadata: |
          [
            {
              "display_name": "Python 3.11 (UBI9)",
              "metadata": {
                "tags": [
                  "minimal"
                ],
                "display_name": "Python 3.11 (UBI9)",
                "image_name": "quay.io/opendatahub/workbench-images@sha256:6dc66e67d1d3548b11249389f29e540ec4aa8733cb63f5c5ce52d52602e3b80d",
                "pull_policy": "IfNotPresent"
              },
              "schema_name": "runtime-image"
            }
          ]
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
      from:
        kind: DockerImage
        name: quay.io/opendatahub/workbench-images@sha256:6dc66e67d1d3548b11249389f29e540ec4aa8733cb63f5c5ce52d52602e3b80d
      name: "minimal"
      referencePolicy:
        type: Source
