"""Unit tests for pylocks_generator exclude-newer helpers."""

from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[3]
# _SCRIPTS = _REPO_ROOT / "scripts"
# if str(_SCRIPTS) not in sys.path:
#     sys.path.insert(0, str(_SCRIPTS))

import scripts.pylocks_generator as pg  # noqa: E402


@pytest.fixture
def repo_root() -> Path:
    return _REPO_ROOT


def test_utc_now_iso_format() -> None:
    s = pg.utc_now_iso()
    assert len(s) == 20
    assert s.endswith("Z")
    assert "T" in s


def test_parse_exclude_newer_equals_form(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile pyproject.toml --exclude-newer=2025-06-01T12:30:45Z --quiet\n"
        'lock-version = "1.0"\n',
        encoding="utf-8",
    )
    assert pg.parse_exclude_newer_from_lockfile(p) == "2025-06-01T12:30:45Z"


def test_parse_exclude_newer_space_form(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile pyproject.toml --exclude-newer 2025-06-01T12:30:45Z --quiet\n"
        'lock-version = "1.0"\n',
        encoding="utf-8",
    )
    assert pg.parse_exclude_newer_from_lockfile(p) == "2025-06-01T12:30:45Z"


def test_parse_exclude_newer_offset_form(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile --exclude-newer=2025-06-01T12:30:45+00:00 x\n"
        'lock-version = "1.0"\n',
        encoding="utf-8",
    )
    assert pg.parse_exclude_newer_from_lockfile(p) == "2025-06-01T12:30:45+00:00"


def test_parse_exclude_newer_missing(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile pyproject.toml --quiet\n"
        'lock-version = "1.0"\n',
        encoding="utf-8",
    )
    assert pg.parse_exclude_newer_from_lockfile(p) is None


def test_parse_exclude_newer_missing_file(tmp_path: Path) -> None:
    assert pg.parse_exclude_newer_from_lockfile(tmp_path / "nope.toml") is None


def test_parse_exclude_newer_real_cpu_lock_header(repo_root: Path) -> None:
    sample = repo_root / "jupyter" / "datascience" / "ubi9-python-3.12" / "uv.lock.d" / "pylock.cpu.toml"
    if not sample.is_file():
        pytest.skip("sample lockfile not present")
    parsed = pg.parse_exclude_newer_from_lockfile(sample)
    assert parsed is not None


def test_resolve_exclude_newer_live_mode(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text("# no exclude\n", encoding="utf-8")
    assert pg.resolve_exclude_newer(p, ci_check=False, live_timestamp="2020-01-01T00:00:00Z") == (
        "2020-01-01T00:00:00Z"
    )


def test_resolve_exclude_newer_ci_parsed(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile --exclude-newer=2099-01-01T00:00:00Z\n",
        encoding="utf-8",
    )
    assert pg.resolve_exclude_newer(p, ci_check=True, live_timestamp="2020-01-01T00:00:00Z") == ("2099-01-01T00:00:00Z")


def test_resolve_exclude_newer_ci_fallback(tmp_path: Path) -> None:
    p = tmp_path / "pylock.toml"
    p.write_text(
        "#    uv pip compile pyproject.toml --quiet\n",
        encoding="utf-8",
    )
    assert pg.resolve_exclude_newer(p, ci_check=True, live_timestamp="2020-01-01T00:00:00Z") == ("2020-01-01T00:00:00Z")


class TestEnsureJsonFormatParam:
    def test_bare_url(self) -> None:
        assert pg.ensure_json_format_param("https://example.com/simple/") == ("https://example.com/simple/?format=json")

    def test_no_trailing_slash(self) -> None:
        assert pg.ensure_json_format_param("https://example.com/simple") == ("https://example.com/simple?format=json")

    def test_already_has_format_json(self) -> None:
        url = "https://example.com/simple/?format=json"
        assert pg.ensure_json_format_param(url) == url

    def test_overwrites_non_json_format(self) -> None:
        assert pg.ensure_json_format_param("https://example.com/simple/?format=html") == (
            "https://example.com/simple/?format=json"
        )

    def test_other_query_params(self) -> None:
        assert pg.ensure_json_format_param("https://example.com/simple/?other=1") == (
            "https://example.com/simple/?other=1&format=json"
        )

    def test_real_aipcc_url(self) -> None:
        url = "https://console.redhat.com/api/pypi/public-rhai/rhoai/3.4/cpu-ubi9/simple/"
        result = pg.ensure_json_format_param(url)
        assert result == url + "?format=json"
        assert pg.ensure_json_format_param(result) == result


def test_get_index_flags_uses_mode_specific_conf_file(tmp_path: Path) -> None:
    build_args = tmp_path / "build-args"
    build_args.mkdir()
    (build_args / "cpu.conf").write_text("INDEX_URL=https://pypi.org/simple/\n", encoding="utf-8")
    (build_args / "konflux.cpu.conf").write_text(
        "INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA1/cpu-ubi9/simple/\n",
        encoding="utf-8",
    )
    log = pg.LogBuffer()

    public_flags = pg.get_index_flags(tmp_path, "cpu", pg.IndexMode.public_index, log)
    rhds_flags = pg.get_index_flags(tmp_path, "cpu", pg.IndexMode.rh_index, log)

    assert public_flags == ["--default-index=https://pypi.org/simple/?format=json"]
    assert rhds_flags == [
        "--default-index=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA1/cpu-ubi9/simple/?format=json"
    ]


def test_generate_requirements_txt_uses_konflux_index_for_rh_locks(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    build_args = tmp_path / "build-args"
    build_args.mkdir()
    (build_args / "cpu.conf").write_text("INDEX_URL=https://pypi.org/simple/\n", encoding="utf-8")
    (build_args / "konflux.cpu.conf").write_text(
        "INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA1/cpu-ubi9/simple/\n",
        encoding="utf-8",
    )
    pylock_dir = tmp_path / "uv.lock.d"
    pylock_dir.mkdir()
    (pylock_dir / "pylock.rhds.cpu.toml").write_text('lock-version = "1.0"\n', encoding="utf-8")

    captured: dict[str, list[str]] = {}

    def fake_run(cmd: list[str], **_: object) -> SimpleNamespace:
        captured["cmd"] = cmd
        Path(cmd[3]).write_text("--index-url https://example.invalid/\n", encoding="utf-8")
        return SimpleNamespace(returncode=0, stdout="", stderr="")

    monkeypatch.setattr(pg.subprocess, "run", fake_run)

    assert pg.generate_requirements_txt(tmp_path, "cpu", pg.IndexMode.rh_index, pg.LogBuffer()) is True
    assert captured["cmd"][2].endswith("uv.lock.d/pylock.rhds.cpu.toml")
    assert captured["cmd"][3].endswith("requirements.rhds.cpu.txt")
    assert captured["cmd"][-1] == "https://console.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA1/cpu-ubi9/simple/"
    assert not (tmp_path / "requirements.cpu.txt").exists()


def test_run_lock_does_not_write_legacy_rhds_lock_alias(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    captured: dict[str, object] = {}

    def fake_run(cmd: list[str], **kwargs: object) -> SimpleNamespace:
        captured["cmd"] = cmd
        cwd = Path(kwargs["cwd"])
        output = cmd[cmd.index("--output-file") + 1]
        (cwd / output).write_text('lock-version = "1.0"\n', encoding="utf-8")
        return SimpleNamespace(returncode=0, stdout="", stderr="")

    monkeypatch.setattr(pg.subprocess, "run", fake_run)

    assert pg.run_lock(
        tmp_path,
        "cpu",
        ["--default-index=https://example.invalid/simple/?format=json"],
        pg.IndexMode.rh_index,
        "3.12",
        upgrade=False,
        ci_check=False,
        live_timestamp="2020-01-01T00:00:00Z",
        log=pg.LogBuffer(),
    )
    assert (tmp_path / "uv.lock.d" / "pylock.rhds.cpu.toml").is_file()
    assert not (tmp_path / "uv.lock.d" / "pylock.cpu.toml").exists()


def test_generate_requirements_txt_uses_odh_paths_for_public_locks(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    build_args = tmp_path / "build-args"
    build_args.mkdir()
    (build_args / "cpu.conf").write_text("INDEX_URL=https://pypi.org/simple/\n", encoding="utf-8")
    pylock_dir = tmp_path / "uv.lock.d"
    pylock_dir.mkdir()
    (pylock_dir / "pylock.odh.cpu.toml").write_text('lock-version = "1.0"\n', encoding="utf-8")

    captured: dict[str, list[str]] = {}

    def fake_run(cmd: list[str], **_: object) -> SimpleNamespace:
        captured["cmd"] = cmd
        return SimpleNamespace(returncode=0, stdout="", stderr="")

    monkeypatch.setattr(pg.subprocess, "run", fake_run)

    assert pg.generate_requirements_txt(tmp_path, "cpu", pg.IndexMode.public_index, pg.LogBuffer()) is True
    assert captured["cmd"][2].endswith("uv.lock.d/pylock.odh.cpu.toml")
    assert captured["cmd"][3].endswith("requirements.odh.cpu.txt")
    assert captured["cmd"][-1] == "https://pypi.org/simple/"


def test_process_directory_auto_generates_both_public_and_konflux_artifacts(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    project_dir = tmp_path / "jupyter" / "minimal" / "ubi9-python-3.12"
    project_dir.mkdir(parents=True)
    (project_dir / "Dockerfile.cpu").write_text("", encoding="utf-8")
    (project_dir / "Dockerfile.konflux.cpu").write_text("", encoding="utf-8")
    build_args = project_dir / "build-args"
    build_args.mkdir()
    (build_args / "cpu.conf").write_text("INDEX_URL=https://pypi.org/simple/\n", encoding="utf-8")
    (build_args / "konflux.cpu.conf").write_text(
        "INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA1/cpu-ubi9/simple/\n",
        encoding="utf-8",
    )

    lock_calls: list[tuple[str, pg.IndexMode]] = []
    requirements_calls: list[tuple[str, pg.IndexMode]] = []

    def fake_run_lock(
        project_dir: Path,
        flavor: str,
        index_flags: list[str],
        mode: pg.IndexMode,
        python_version: str,
        upgrade: bool,
        ci_check: bool,
        live_timestamp: str,
        log: pg.LogBuffer,
    ) -> bool:
        lock_calls.append((flavor, mode))
        return True

    def fake_generate_requirements_txt(
        project_dir: Path,
        flavor: str,
        mode: pg.IndexMode,
        log: pg.LogBuffer,
    ) -> bool:
        requirements_calls.append((flavor, mode))
        return True

    monkeypatch.setattr(pg, "run_lock", fake_run_lock)
    monkeypatch.setattr(pg, "generate_requirements_txt", fake_generate_requirements_txt)

    _tdir, success, _log = pg.process_directory(
        project_dir,
        pg.IndexMode.auto,
        upgrade=False,
        ci_check=False,
        live_timestamp="2020-01-01T00:00:00Z",
    )

    assert success is True
    assert lock_calls == [
        ("cpu", pg.IndexMode.public_index),
        ("cpu", pg.IndexMode.rh_index),
    ]
    assert requirements_calls == [
        ("cpu", pg.IndexMode.public_index),
        ("cpu", pg.IndexMode.rh_index),
    ]
