FROM quay.io/opendatahub/workbench-images:cuda-base AS base

ARG PROFILE
ARG PYLOCK_FLAVOR
COPY pyproject.toml ./
COPY uv.lock.d/pylock.${PROFILE}.${PYLOCK_FLAVOR}.toml ./pylock.toml

RUN pip install --no-cache-dir --no-deps --requirement=./pylock.toml

EXPOSE 8888
CMD ["jupyter", "lab"]
