LABEL_REGISTRY_PREFIX=opendatahub
PRODUCT=odh
RELEASE=3.5

BASE_IMAGE_CPU=quay.io/opendatahub/odh-base-image-cpu-py312-c9s:latest
BASE_IMAGE_CUDA_13=quay.io/opendatahub/odh-base-image-cuda-py312-c9s:v13.0
BASE_IMAGE_CUDA_12=quay.io/opendatahub/odh-base-image-cuda-py312-c9s:v12.9
BASE_IMAGE_ROCM=quay.io/opendatahub/odh-base-image-rocm-py312-c9s:v7.1

BASE_IMAGE_WORKBENCH_MINIMAL_CPU=${BASE_IMAGE_CPU}
BASE_IMAGE_WORKBENCH_MINIMAL_CUDA=${BASE_IMAGE_CUDA_13}
BASE_IMAGE_WORKBENCH_MINIMAL_ROCM=${BASE_IMAGE_ROCM}
BASE_IMAGE_WORKBENCH_PYTORCH_CUDA=${BASE_IMAGE_CUDA_13}
BASE_IMAGE_WORKBENCH_PYTORCH_ROCM=${BASE_IMAGE_ROCM}
BASE_IMAGE_WORKBENCH_PYTORCH_LLMCOMPRESSOR_CUDA=${BASE_IMAGE_CUDA_13}
BASE_IMAGE_WORKBENCH_TENSORFLOW_CUDA=${BASE_IMAGE_CUDA_12}
BASE_IMAGE_WORKBENCH_TENSORFLOW_ROCM=${BASE_IMAGE_ROCM}
BASE_IMAGE_WORKBENCH_TRUSTYAI_CPU=${BASE_IMAGE_CPU}
BASE_IMAGE_WORKBENCH_CODESERVER_CPU=${BASE_IMAGE_CPU}

BASE_IMAGE_RUNTIME_MINIMAL_CPU=${BASE_IMAGE_CPU}
BASE_IMAGE_RUNTIME_PYTORCH_CUDA=${BASE_IMAGE_CUDA_13}
BASE_IMAGE_RUNTIME_PYTORCH_ROCM=${BASE_IMAGE_ROCM}
BASE_IMAGE_RUNTIME_PYTORCH_LLMCOMPRESSOR_CUDA=${BASE_IMAGE_CUDA_13}
BASE_IMAGE_RUNTIME_TENSORFLOW_CUDA=${BASE_IMAGE_CUDA_12}
BASE_IMAGE_RUNTIME_TENSORFLOW_ROCM=${BASE_IMAGE_ROCM}
