LABEL_REGISTRY_PREFIX=rhoai
PRODUCT=rhoai
RELEASE=3.5

BASE_IMAGE_CPU=quay.io/aipcc/base-images/cpu:3.5.0-ea.2-1780972106
BASE_IMAGE_CUDA_13=quay.io/aipcc/base-images/cuda-13.0-el9.6:3.5.0-ea.2-1780972037
BASE_IMAGE_CUDA_12=quay.io/aipcc/base-images/cuda-12.9-el9.6:3.5.0-ea.2-1780972037
BASE_IMAGE_ROCM=quay.io/aipcc/base-images/rocm-7.1-el9.6:3.5.0-ea.2-1780597719

BASE_IMAGE_WORKBENCH_MINIMAL_CPU=${BASE_IMAGE_CPU}
BASE_IMAGE_WORKBENCH_MINIMAL_CUDA=${BASE_IMAGE_CUDA_STABLE}
BASE_IMAGE_WORKBENCH_MINIMAL_ROCM=${BASE_IMAGE_ROCM}
BASE_IMAGE_WORKBENCH_PYTORCH_CUDA=${BASE_IMAGE_CUDA_13}
BASE_IMAGE_WORKBENCH_PYTORCH_ROCM=${BASE_IMAGE_ROCM}
BASE_IMAGE_WORKBENCH_PYTORCH_LLMCOMPRESSOR_CUDA=${BASE_IMAGE_CUDA_13}
BASE_IMAGE_WORKBENCH_TENSORFLOW_CUDA=${BASE_IMAGE_CUDA_12}
BASE_IMAGE_WORKBENCH_TENSORFLOW_ROCM=${BASE_IMAGE_ROCM}
BASE_IMAGE_WORKBENCH_TRUSTYAI_CPU=${BASE_IMAGE_CPU}
BASE_IMAGE_WORKBENCH_CODESERVER_CPU=${BASE_IMAGE_CPU}

BASE_IMAGE_RUNTIME_MINIMAL_CPU=${BASE_IMAGE_CPU}
BASE_IMAGE_RUNTIME_PYTORCH_CUDA=${BASE_IMAGE_CUDA_13}
BASE_IMAGE_RUNTIME_PYTORCH_ROCM=${BASE_IMAGE_ROCM}
BASE_IMAGE_RUNTIME_PYTORCH_LLMCOMPRESSOR_CUDA=${BASE_IMAGE_CUDA_13}
BASE_IMAGE_RUNTIME_TENSORFLOW_CUDA=${BASE_IMAGE_CUDA_12}
BASE_IMAGE_RUNTIME_TENSORFLOW_ROCM=${BASE_IMAGE_ROCM}
