---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    opendatahub.io/notebook-image-order: "14"
    opendatahub.io/notebook-image-name: "Jupyter Minimal CPU Python 3.12"
  name: jupyter-minimal-notebook
$patch: merge
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "Python", "version": "v3.12"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "JupyterLab","version": "4.2"}
          ]
        opendatahub.io/notebook-build-commit: odh-workbench-jupyter-minimal-cpu-py312-ubi9-commit-n_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-workbench-jupyter-minimal-cpu-py312-ubi9-n_PLACEHOLDER
      name: "2025.2-beta"
      referencePolicy:
        type: Source
