name: Weekly Pipfile.locks renewal on [main] branch

on:
  schedule:
    - cron: "0 22 * * 1"  # Triggers the workflow every Monday at 22:00 UTC
  workflow_dispatch:
    inputs:
      branch:
        description: 'Specify the branch to run this workflow'
        required: false
        default: 'main'
      python_version:
        description: 'Python version to update Pipfile.lock'
        required: false
        default: '3.11'  # Set a default if needed
        options:
          - '3.9'
          - '3.11'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allows the GitHub Actions bot to commit and push changes

    steps:
      # Checkout the specified branch (or default to 'main')
      - name: Checkout code from the specified branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      # Setup Python environment with the specified version (or default to '3.11')
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python_version }}

      # Install pipenv
      - name: Install pipenv
        run: pip install pipenv

      # Run makefile recipe to refresh Pipfile.lock and push changes back to the branch
      - name: Run make refresh-pipfilelock-files and push the changes
        run: |
          make refresh-pipfilelock-files PYTHON_VERSION=${{ github.event.inputs.python_version }}
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update the Pipfile.lock via the weekly workflow action"
          git push origin ${{ github.event.inputs.branch }}
